# Generated by Django 5.2.4 on 2025-08-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='foods/')),
                ('price', models.IntegerField()),
                ('kind', models.CharField(choices=[('Sandwich', 'sandwich'), ('Others', 'others'), ('Pizza', 'pizza'), ('Drink', 'drink')])),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
